import { NextRequest, NextResponse } from "next/server";
import { decryptOutlookTokens, encryptOutlookTokens, getOutlookConnection, OutlookCalendarChoice, refreshOutlookTokens, saveOutlookConnection } from "@/lib/outlookServer";
import { verifyFirebaseToken } from "@/lib/gmailServer";
export const runtime = "nodejs";
const auth = (request: NextRequest) => request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") || "";
const graph = async (path: string, token: string) => { const response = await fetch(`https://graph.microsoft.com/v1.0/${path}`, { headers: { authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? "Outlook Calendar permission is missing. Reconnect Outlook and approve calendar access." : body?.error?.message || "Outlook Calendar could not be reached."); return body; };
async function connectionFor(idToken: string) { const { uid } = await verifyFirebaseToken(idToken); const connection = await getOutlookConnection(uid, idToken); if (!connection?.encrypted) throw new Error("Connect Outlook Calendar first."); const original = decryptOutlookTokens(connection.encrypted); const tokens = await refreshOutlookTokens(original); const current = tokens.access_token === original.access_token ? connection : { ...connection, encrypted: encryptOutlookTokens(tokens) }; if (current !== connection) await saveOutlookConnection(uid, idToken, current); return { uid, connection: current, accessToken: tokens.access_token }; }
export async function GET(request: NextRequest) { try { const idToken = auth(request); if (!idToken) return NextResponse.json({ error: "Sign in first." }, { status: 401 }); const { uid, connection, accessToken } = await connectionFor(idToken); const body = await graph("me/calendars?$select=id,name,color,isDefaultCalendar", accessToken); const calendars: OutlookCalendarChoice[] = (body.value || []).map((item: any): OutlookCalendarChoice => ({ id: String(item.id), name: String(item.name || "Outlook calendar"), color: typeof item.color === "string" ? item.color : undefined, primary: Boolean(item.isDefaultCalendar) })); const remembered: string[] = connection.selectedCalendarIds || []; const selectedCalendarIds: string[] = (remembered.length ? remembered : calendars.map((calendar: OutlookCalendarChoice) => calendar.id)).filter((id: string) => calendars.some((calendar: OutlookCalendarChoice) => calendar.id === id)); await saveOutlookConnection(uid, idToken, { ...connection, calendars, selectedCalendarIds }); return NextResponse.json({ connected: true, calendars, selectedCalendarIds }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not load Outlook Calendar." }, { status: 500 }); } }
export async function PUT(request: NextRequest) { try { const idToken = auth(request); if (!idToken) return NextResponse.json({ error: "Sign in first." }, { status: 401 }); const body = await request.json(); if (!Array.isArray(body.selectedCalendarIds)) return NextResponse.json({ error: "Choose at least one calendar." }, { status: 400 }); const { uid, connection } = await connectionFor(idToken); await saveOutlookConnection(uid, idToken, { ...connection, selectedCalendarIds: body.selectedCalendarIds.filter((id: unknown): id is string => typeof id === "string") }); return NextResponse.json({ ok: true }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not save Outlook Calendar choices." }, { status: 500 }); } }
export async function DELETE(request: NextRequest) { try { const idToken = auth(request); if (!idToken) return NextResponse.json({ error: "Sign in first." }, { status: 401 }); const { uid } = await verifyFirebaseToken(idToken); await saveOutlookConnection(uid, idToken, null); return NextResponse.json({ connected: false }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not disconnect Outlook." }, { status: 500 }); } }
