import type { WorkHubState } from "@/app/components/OSDashboards";

export const DEMO_PROJECTS = [
  {
    name: "LifeOS Platform",
    desc: "Core platform development and feature releases",
    progress: 72,
    color: "#625af6",
    iconName: "FolderKanban" as const,
    tasks: 12,
    kind: "finishable" as const,
    scope: "work" as const,
  },
  {
    name: "Client Projects",
    desc: "Active client delivery and support",
    progress: 58,
    color: "#ff6b6b",
    iconName: "BriefcaseBusiness" as const,
    tasks: 18,
    kind: "finishable" as const,
    scope: "work" as const,
  },
  {
    name: "AI Integration",
    desc: "LLM features and automation",
    progress: 45,
    color: "#4ecdc4",
    iconName: "Sparkles" as const,
    tasks: 8,
    kind: "finishable" as const,
    scope: "work" as const,
  },
  {
    name: "Design System",
    desc: "Component library and design tokens",
    progress: 88,
    color: "#95e1d3",
    iconName: "Palette" as const,
    tasks: 5,
    kind: "finishable" as const,
    scope: "work" as const,
  },
  {
    name: "Research & Learning",
    desc: "Continuous skill development",
    progress: 35,
    color: "#ffe66d",
    iconName: "BookOpen" as const,
    tasks: 6,
    kind: "maintenance" as const,
    scope: "work" as const,
  },
  {
    name: "Business Development",
    desc: "Partnerships and growth initiatives",
    progress: 28,
    color: "#a8dadc",
    iconName: "Globe" as const,
    tasks: 4,
    kind: "maintenance" as const,
    scope: "work" as const,
  },
  {
    name: "Mentoring Program",
    desc: "Develop and mentor junior developers",
    progress: 62,
    color: "#f4a261",
    iconName: "Code2" as const,
    tasks: 7,
    kind: "maintenance" as const,
    scope: "work" as const,
  },
  {
    name: "Open Source",
    desc: "Contributing to community projects",
    progress: 22,
    color: "#2a9d8f",
    iconName: "Globe" as const,
    tasks: 3,
    kind: "maintenance" as const,
    scope: "work" as const,
  },
];

export const DEMO_TASKS = [
  {
    id: 10001,
    title: "Review PRs for LifeOS core",
    project: "LifeOS Platform",
    color: "#625af6",
    due: "2026-07-29",
    priority: "High" as const,
    focusMinutes: 45,
    energy: "High" as const,
    classId: undefined,
    done: false,
    canceled: false,
  },
  {
    id: 10002,
    title: "Implement AI task breakdown feature",
    project: "LifeOS Platform",
    color: "#625af6",
    due: "2026-08-05",
    priority: "High" as const,
    focusMinutes: 60,
    energy: "High" as const,
    classId: undefined,
    done: false,
    canceled: false,
  },
  {
    id: 10003,
    title: "Deploy TechCorp performance updates",
    project: "Client Projects",
    color: "#ff6b6b",
    due: "2026-07-31",
    priority: "High" as const,
    focusMinutes: 90,
    energy: "High" as const,
    classId: undefined,
    done: false,
    canceled: false,
  },
  {
    id: 10004,
    title: "Design system v2.0 release planning",
    project: "Design System",
    color: "#95e1d3",
    due: "2026-08-10",
    priority: "Medium" as const,
    focusMinutes: 45,
    energy: "Medium" as const,
    classId: undefined,
    done: false,
    canceled: false,
  },
  {
    id: 10005,
    title: "Mentor weekly 1-1 with junior dev",
    project: "Mentoring Program",
    color: "#f4a261",
    due: "2026-07-30",
    priority: "Medium" as const,
    focusMinutes: 30,
    energy: "Medium" as const,
    classId: undefined,
    done: false,
    canceled: false,
  },
  {
    id: 10006,
    title: "Research LLM fine-tuning techniques",
    project: "Research & Learning",
    color: "#ffe66d",
    due: "2026-08-15",
    priority: "Low" as const,
    focusMinutes: 60,
    energy: "Low" as const,
    classId: undefined,
    done: false,
    canceled: false,
  },
];

export const DEMO_EVENTS = [
  {
    id: "evt-001",
    title: "Client meeting: TechCorp Q3 Planning",
    start: "2026-07-30T14:00:00Z",
    source: "LifeOS" as const,
    color: "#ff6b6b",
    notes: "Discuss Q3 roadmap and priorities",
  },
  {
    id: "evt-002",
    title: "Design System sync",
    start: "2026-07-31T10:00:00Z",
    source: "LifeOS" as const,
    color: "#95e1d3",
    notes: "Component library review",
  },
  {
    id: "evt-003",
    title: "Weekly team standup",
    start: "2026-08-01T09:00:00Z",
    source: "LifeOS" as const,
    color: "#625af6",
  },
  {
    id: "evt-004",
    title: "Mentoring 1-1: Sarah Chen",
    start: "2026-08-01T15:00:00Z",
    source: "LifeOS" as const,
    color: "#f4a261",
    notes: "Career development discussion",
  },
  {
    id: "evt-005",
    title: "AI Research Conference",
    start: "2026-08-10T09:00:00Z",
    source: "LifeOS" as const,
    color: "#4ecdc4",
    notes: "LLM applications and trends",
  },
];

export function createWorkOSDemoData(): WorkHubState {
  return {
    portfolio: [
      {
        id: "port-1",
        title: "LifeOS Platform",
        subtitle: "Personal Operating System",
        notes: "A comprehensive life management platform combining task management, project tracking, calendar integration, and contextual work management. Built with Next.js, React, Firebase, and Framer Motion.",
        category: "Software",
        url: "https://lifeos.app",
        imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80",
        createdAt: new Date().toISOString(),
      },
      {
        id: "port-2",
        title: "AI Task Breakdown Assistant",
        subtitle: "NLP-powered task decomposition",
        notes: "Intelligent system that automatically breaks down complex tasks into actionable subtasks using natural language processing. Integrates with task management for seamless workflow.",
        category: "AI/ML",
        url: "https://github.com/you/task-breakdown",
        createdAt: new Date().toISOString(),
      },
      {
        id: "port-3",
        title: "Design System Components",
        subtitle: "Reusable component library",
        notes: "Accessible, responsive React component library with comprehensive Storybook documentation. 40+ production-ready components including charts, forms, and data tables.",
        category: "Design",
        url: "https://components.example.com",
        createdAt: new Date().toISOString(),
      },
      {
        id: "port-4",
        title: "Data Analytics Dashboard",
        subtitle: "Real-time metrics visualization",
        notes: "Interactive dashboard for business analytics with real-time data updates, custom report generation, and export capabilities. Helps teams make data-driven decisions.",
        category: "Software",
        createdAt: new Date().toISOString(),
      },
    ],
    clients: [
      {
        id: "client-1",
        title: "TechCorp Inc",
        subtitle: "Enterprise Software Company",
        notes: "Fortune 500 tech company. Long-term partnership for platform maintenance and feature development.",
        category: "Client",
        createdAt: new Date().toISOString(),
      },
      {
        id: "client-2",
        title: "StartupVentures",
        subtitle: "Early-stage SaaS",
        notes: "Fast-growing SaaS startup needing rapid MVP development and iterations based on user feedback.",
        category: "Client",
        createdAt: new Date().toISOString(),
      },
      {
        id: "client-3",
        title: "Design Studio Pro",
        subtitle: "Creative Agency",
        notes: "Full-service design agency requiring web development and technical implementation of designs.",
        category: "Client",
        createdAt: new Date().toISOString(),
      },
    ],
    skills: [
      {
        id: "skill-1",
        title: "Frontend Development",
        subtitle: "React & Modern Web",
        category: "Technical",
        notes: "Deep expertise in React, Next.js, TypeScript, and modern frontend architecture patterns.",
        createdAt: new Date().toISOString(),
      },
      {
        id: "skill-2",
        title: "Full-stack Development",
        subtitle: "Backend & Infrastructure",
        category: "Technical",
        notes: "Node.js, Python, database design, and cloud infrastructure (AWS, Firebase, Vercel).",
        createdAt: new Date().toISOString(),
      },
      {
        id: "skill-3",
        title: "Product Design",
        subtitle: "UX/UI & User Research",
        category: "Design",
        notes: "User research, wireframing, prototyping, and design systems. Figma expert.",
        createdAt: new Date().toISOString(),
      },
      {
        id: "skill-4",
        title: "AI/ML Integration",
        subtitle: "LLMs & Natural Language",
        category: "Technical",
        notes: "Experience integrating LLMs like GPT-4, Claude, and implementing NLP features.",
        createdAt: new Date().toISOString(),
      },
      {
        id: "skill-5",
        title: "Technical Leadership",
        subtitle: "Mentoring & Architecture",
        category: "Leadership",
        notes: "Mentoring junior developers, architectural decision-making, and system design.",
        createdAt: new Date().toISOString(),
      },
    ],
    goals: [
      {
        id: "goal-1",
        title: "Ship AI-powered features to 100K users",
        subtitle: "Product milestone",
        notes: "Launch machine learning features that improve user experience and drive engagement.",
        category: "Professional",
        createdAt: new Date().toISOString(),
      },
      {
        id: "goal-2",
        title: "Build design system used by 50+ developers",
        subtitle: "Technical leadership",
        notes: "Create comprehensive, well-documented component library that standardizes UI development.",
        category: "Professional",
        createdAt: new Date().toISOString(),
      },
      {
        id: "goal-3",
        title: "Achieve 99.99% uptime on production",
        subtitle: "Reliability milestone",
        notes: "Implement robust monitoring, auto-scaling, and disaster recovery procedures.",
        category: "Professional",
        createdAt: new Date().toISOString(),
      },
      {
        id: "goal-4",
        title: "Mentor 10 junior developers to senior roles",
        subtitle: "Leadership impact",
        notes: "Develop and mentor junior team members through structured 1-1s and knowledge sharing.",
        category: "Professional",
        createdAt: new Date().toISOString(),
      },
      {
        id: "goal-5",
        title: "Publish technical articles on Modern Web Dev",
        subtitle: "Thought leadership",
        notes: "Share expertise through comprehensive blog posts on advanced frontend patterns.",
        category: "Professional",
        createdAt: new Date().toISOString(),
      },
    ],
  };
}

export const DEMO_MODE_ENABLED = process.env.NEXT_PUBLIC_DEMO_MODE === "true";
